Feature/dipa 185 compare templates increments
DiPA-Projekt/dipa-hub pull request #113
Opened 2021-01-22 08:17 UTC by irenenguyen3095

2021-01-22 08:25 UTC, beckerjohannes requested changes

2021-01-22 08:25 UTC, beckerjohannes commented on server/src/test/java/online/dipa/hub/persistence/entities/BaseEntityTest.java
> +//          final DummyEntity dummyB = new DummyEntity();
@irenenguyen3095 warum sind alle tests auskommentiert?

2021-01-22 11:17 UTC, irenenguyen3095 commented on server/src/test/java/online/dipa/hub/persistence/entities/BaseEntityTest.java
> +//          final DummyEntity dummyB = new DummyEntity();
Dieser PR ist noch nicht im Review, ich lasse die Tests schon wieder :)

2021-01-22 16:37 UTC, Bock4Soft requested changes
Generell müssen wir ganz bald mal den Code aufräumen und Teile wiederverwenden, aber aktuell fehlt dafür leider die Zeit

2021-01-22 16:37 UTC, Bock4Soft commented on frontend/projects/dipa-frontend/src/app/modules/gantt/templates-view/templates-view.component.ts
> +        this.selectedTemplatesList.push(templatesData.find(t => t.name === 'aktuell'));
auch lieber über Konstante in der Komponente: private CURRENT_TEMPLATE = 'aktuell'; oder so

2021-01-22 16:37 UTC, Bock4Soft commented on frontend/projects/dipa-frontend/src/app/modules/gantt/templates-view/templates-view.component.ts
> +        // this.standardName = this.standardTemplatesList[this.selectedStandardTemplateIndex].name;
left over comment

2021-01-22 16:37 UTC, Bock4Soft commented on frontend/projects/dipa-frontend/src/app/modules/gantt/templates-view/templates-view.component.ts
> +  getNexItemList(listItems, currentIndex): number {
getNextItemList

2021-01-22 16:37 UTC, Bock4Soft commented on frontend/projects/dipa-frontend/src/app/modules/gantt/templates-view/templates-view.component.ts
> +    return currentIndex;
currentIndex = (currentIndex + 1) % listItems.length
wäre glaube ich auch eine schicke Lösung, aber nicht ganz so wichtig

2021-01-22 16:37 UTC, Bock4Soft commented on frontend/projects/dipa-frontend/src/app/modules/gantt/templates-view/templates-view.component.spec.ts
> +// import {NavMenuListItemComponent} from '../../shared/nav-menu-list-item/nav-menu-list-item.component';
unused import

2021-01-22 16:37 UTC, Bock4Soft commented on frontend/projects/dipa-frontend/src/app/modules/gantt/templates-view/templates-view.component.spec.ts
> +// import {NavMenuListItemComponent} from '../../shared/nav-menu-list-item/nav-menu-list-item.component';
Schmeiß am besten templates.component.spec.ts und templates-view.component.spec.ts raus... wir machen Test für neue Komponenten jetzt erstmal nur nach Bedarf

2021-01-23 20:07 UTC, Bock4Soft approved these changes

2021-01-23 20:30 UTC, merged