feat: DIPA-236 rename toolkits to project-checklist, set routing
DiPA-Projekt/dipa-hub pull request #155
Opened 2021-02-01 12:22 UTC by irenenguyen3095

- rename toolkits to project-checklist
- set routing

2021-02-01 12:29 UTC, deleonio requested changes

2021-02-01 12:29 UTC, deleonio commented on frontend/projects/dipa-frontend/src/app/modules/gantt/project-checklist/project-checklist.component.ts
> +  constructor() {}
keine leeren constructor'en

2021-02-01 12:29 UTC, deleonio commented on frontend/projects/dipa-frontend/src/app/modules/gantt/project-checklist/project-checklist.component.ts
> +export class ProjectChecklistComponent implements OnInit {
unused OnInit - interface raus

2021-02-01 12:29 UTC, deleonio commented on frontend/projects/dipa-frontend/src/app/modules/gantt/project-checklist/project-checklist.component.ts
> +  ngOnInit(): void {}
unused - raus

2021-02-01 12:29 UTC, deleonio commented on frontend/projects/dipa-frontend/src/app/modules/gantt/sidenav/sidenav.component.ts
>          route: 'gantt/' + this.selectedTimelineId + '/templates',
So schreiben:

```ts
route: `gantt/${this.selectedTimelineId}/project-checklist`,
```



```

2021-02-02 20:45 UTC, deleonio requested changes

2021-02-02 20:45 UTC, deleonio commented on frontend/projects/dipa-frontend/src/app/modules/gantt/sidenav/sidenav.component.ts
>        this.timelinesSubscription = this.timelinesService.getTimelines().subscribe((data) => {
Sehr gut - Hier sehe ich aktuell noch ein Problem.

2021-02-03 11:03 UTC, Bock4Soft commented on frontend/projects/dipa-frontend/src/app/modules/gantt/sidenav/sidenav.component.ts
>    ngOnInit(): void {
oh ja stimmt... werde ich mir mal genauer anschauen. aber ich jetzt kein spezifisches Problem für diesen PR

2021-02-03 11:07 UTC, irenenguyen3095 commented on frontend/projects/dipa-frontend/src/app/modules/gantt/sidenav/sidenav.component.ts
>        this.timelinesSubscription = this.timelinesService.getTimelines().subscribe((data) => {
soll ich pasreInt(param.id) verwenden?

2021-02-04 14:06 UTC, Bock4Soft approved these changes
Sieht gut aus

2021-02-04 14:07 UTC, merged