feat: DIPA-215 header data project
DiPA-Projekt/dipa-hub pull request #160
Opened 2021-02-02 16:56 UTC by irenenguyen3095

2021-02-02 21:46 UTC, Bock4Soft requested changes
Ansonsten sieht es gut aus

2021-02-02 21:46 UTC, Bock4Soft commented on server/src/main/java/online/dipa/hub/convert/ProjectTemplateToProjectConverter.java
> +        return project;
return new Project().id(template.getId())
                             .name(template.getName())
                             .akz(template.getAKZ())
                             .client(template.getClient())
                             .department(template.getDepartment())
                             .projectOwner(template.getProjectOwner())
                             .projectSize(Project.ProjectSizeEnum.fromValue(template.getProjectSize()));

2021-02-02 21:46 UTC, Bock4Soft commented on server/src/main/java/online/dipa/hub/services/ProjectService.java
> +                    if (sessionProject.getProject() == null) {
t.getId() kann potenziell ne NullPointerException werfen. Kann man damit verhindern:

.filter(Objects::nonNull)
                .forEach(t -> {

2021-02-02 21:46 UTC, Bock4Soft commented on server/src/main/java/online/dipa/hub/convert/ProjectTemplateToTimelineConverter.java
> +public class ProjectTemplateToTimelineConverter implements Converter<ProjectEntity, Timeline> {
Eher ProjectEntityToTimelineConverter, oder?

2021-02-02 21:46 UTC, Bock4Soft commented on server/src/main/java/online/dipa/hub/convert/ProjectTemplateToProjectConverter.java
> +public class ProjectTemplateToProjectConverter implements Converter<ProjectEntity, Project> {
Eher ProjectEntityToProjectConverter, oder?

2021-02-04 14:37 UTC, irenenguyen3095 reviewed
sieht gut aus!

2021-02-04 15:49 UTC, merged