refactor: DIPA-236 refactoring
DiPA-Projekt/dipa-hub pull request #186
Opened 2021-02-11 08:45 UTC by irenenguyen3095

- split into several API controllers, services
- create sessionState
- improve code

2021-02-11 14:38 UTC, Bock4Soft commented on server/src/main/java/online/dipa/hub/services/TimelineTemplateService.java
> +        TimelineState sessionTimeline = getSessionTimelines().get(timelineId);
Wir müssen bei einigen Methoden nochmal über die Namen schauen... die sind noch nicht so sprechend

2021-02-17 07:37 UTC, Bock4Soft approved these changes

2021-02-17 15:28 UTC, beckerjohannes requested changes

2021-02-17 15:28 UTC, beckerjohannes commented on open-api/src/main/resources/dipa-hub.yaml
> +    $ref: "paths/updateTimelineTemplate.yml"
Aktuell ist die API hier an div. Stellen nicht REST konform, da HTTP-Verbs bspw. nicht korrekt eingesetzt werden.

Beispiel:

```yaml
  /timelines/{timelineId}/increments:
    $ref: "paths/increments.yml"
  /timelines/{timelineId}/increments/add:
    $ref: "paths/addIncrement.yml"
  /timelines/{timelineId}/increments/delete:
    $ref: "paths/deleteIncrement.yml"
```
Sowohl addIncrements, als auch deleteIncrement haben "PATCH" als Verb. Eigentlich nach Rest-Logik wäre das alles ein "path" mit unterschiedlichen Verbs.

Also 
```yaml
  /timelines/{timelineId}/increments:
    $ref: "paths/increments.yml"
```
mit 
```yaml
get:
  ....
put:
  ....
delete:
  ....
```
Gleiches gilt für die `/update` Paths. Das sind eigentlich `PATCH` auf der entsprechenden Resource. Umgekehrt wäre die timeline-ops eher ein `/command`  mit `PUT` weil man ein komplexes Commando ablegt und nicht einfach Werte der "Timeline" ändert. 

@Bock4Soft an der Stelle bin ich in den Timeline-Ops darüber gestolpert, das der OperationType einfach freie String sind, warum nicht als Enum, dann wäre die Kommunikation irgendwie sicher gestellt:

```java
        switch (inlineObject.getOperation()) {
            case "moveTimeline": timelineService.moveTimelineByDays(timelineId, inlineObject.getDays());
                break;
            case "moveTimelineStart": timelineService.moveTimelineStartByDays(timelineId, inlineObject.getDays());
                break;
            case "moveTimelineEnd": timelineService.moveTimelineEndByDays(timelineId, inlineObject.getDays());
                break;
            case "moveMilestone": timelineService.moveMileStoneByDays(timelineId, inlineObject.getDays(), inlineObject.getMovedMilestoneId());
                break;
            default:
                return ResponseEntity.notFound().build();
        }
```

-

2021-02-17 15:28 UTC, beckerjohannes commented on open-api/src/main/resources/paths/updateTimelineTemplate.yml
> -    - templates
Siehe anmerkung von oben, korrekte Anwendung von Pfaden und Verbs.

2021-02-17 15:28 UTC, beckerjohannes commented on server/src/main/java/online/dipa/hub/services/MilestoneService.java
> +@Transactional
Nachdem die Services (zumindest die zwei die ich gesehen habe bis jetzt) keinen Zustand haben (keine Attribute die nicht `@Autowired` sind) kann der `@SessionScope` weg. Erzeugt nur unnötig overhead.

2021-02-17 16:29 UTC, beckerjohannes commented on open-api/src/main/resources/paths/increments.yml
> +  responses:
@Bock4Soft genau so, aber jetzt kannst Du "Common Parameters" machen (siehe https://swagger.io/docs/specification/describing-parameters/) Überschrift "Common Parameters"

2021-02-18 12:28 UTC, merged