Feature/DIPA-170 planning time increment
DiPA-Projekt/dipa-hub pull request #60
Opened 2020-12-17 10:45 UTC by irenenguyen3095

Add 14 days to the beginning of each increment

2020-12-22 05:19 UTC, deleonio requested changes

2020-12-22 05:19 UTC, deleonio commented on server/src/main/java/online/dipa/hub/services/TimelineService.java
> +            long newDaysBetween = DAYS.between(increment.getStart().plusDays(14), increment.getEnd());
Hallo @irenenguyen3095 ,

ist der PR redundant zu PR #62 ?

2020-12-22 09:36 UTC, irenenguyen3095 commented on server/src/main/java/online/dipa/hub/services/TimelineService.java
> +            long newDaysBetween = DAYS.between(increment.getStart().plusDays(14), increment.getEnd());
Hi @deleonio,
ich habe die Branches gemerged, bevor ich die PRs erstellt habe. Hab jetzt alle PRs etwas bereinigt. Tut mir leid, dass es etwas verwirrend war.
VG Nhan

2020-12-25 07:07 UTC, deleonio approved these changes

2020-12-25 07:07 UTC, merged