Feat: DIPA-155, DIPA-157 milestones status
DiPA-Projekt/dipa-hub pull request #69
Opened 2021-01-04 09:55 UTC by irenenguyen3095

- open milestone's menu
- save milestone's status

2021-01-05 15:23 UTC, deleonio commented
@irenenguyen3095 

Der Fix ist in einem separaten PR https://github.com/DiPA-Projekt/dipa-hub/pull/72

So kannst Du die Änderungen nachvollziehen.

2021-01-05 16:42 UTC, irenenguyen3095 commented
@deleonio 
ich habe deinen Fix in diesem Branch angepasst.
Bitte diesen PR reviewen, danke dir!

2021-01-07 14:30 UTC, Bock4Soft requested changes

2021-01-07 14:30 UTC, Bock4Soft commented on server/src/main/java/online/dipa/hub/convert/MilestoneTemplateToMilestoneConverter.java
> +        }
Bitte keine Strings in switch-Anweisungen oder ähnlichem verwenden. Ich denke das kann dadurch ersetzt werden:
`.status(Milestone.StatusEnum.fromValue(templateEntity.getStatus()));`

2021-01-07 15:25 UTC, irenenguyen3095 commented on frontend/projects/dipa-frontend/src/app/modules/gantt/chart/chart-elements/MilestonesArea.ts
> +  private updateMilestoneStyle(milestoneId): void {
@Bock4Soft  ich habe diese Methode so genannt

2021-01-07 20:12 UTC, Bock4Soft approved these changes

2021-01-07 20:14 UTC, merged